import os
import json
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

def handler(event, context):
    # Retrieve configuration from environment variables (set these in Netlify UI)
    SMTP_HOST = "smtp.gmail.com"
    SMTP_PORT = 587
    SMTP_USERNAME = os.environ.get("SMTP_USERNAME", "akshitsolanki2@gmail.com")
    SMTP_PASSWORD = os.environ.get("SMTP_PASSWORD", "zruoepechmafcauw")
    SMTP_FROM_EMAIL = os.environ.get("SMTP_FROM_EMAIL", "akshitsolanki2@gmail.com")
    RECIPIENTS = os.environ.get("SEND_MAIL_TO", "akshitsolanki2@gmail.com,aarzu.dangi@gmail.com").split(",")

    try:
        print(f"DEBUG: Attempting to send email to {RECIPIENTS}")
        msg = MIMEMultipart()
        msg['From'] = SMTP_FROM_EMAIL
        msg['To'] = ", ".join(RECIPIENTS)
        msg['Subject'] = "💍 Official Valentine Agreement - Akshit & Aarzu"

        date_str = datetime.now().strftime("%B %d, %Y")
        
        body = f"""
        <html>
        <body style="font-family: 'Arial', sans-serif; color: #333; line-height: 1.6; background-color: #fff5f6; padding: 20px;">
            <div style="max-width: 600px; margin: auto; background: white; padding: 40px; border-radius: 20px; border: 2px solid #ff6b81; box-shadow: 0 10px 30px rgba(0,0,0,0.1);">
                <h1 style="color: #ff4d6d; text-align: center; border-bottom: 2px solid #ffb3c1; padding-bottom: 10px;">Lover's Agreement</h1>
                
                <p style="text-align: right; font-weight: bold; color: #777;">Date: {date_str}</p>
                
                <p style="font-size: 1.1rem;">This agreement is made solemnly between:</p>
                
                <div style="background: #fff0f3; padding: 15px; border-radius: 10px; margin: 20px 0;">
                    <p><strong>Party A:</strong> Akshit Solanki</p>
                    <p><strong>Party B:</strong> Aarzu Dangi</p>
                </div>
                
                <h3 style="color: #d63384;">Terms of Love:</h3>
                <ul>
                    <li>The parties agree to love, cherish, and annoy each other forever.</li>
                    <li>Aarzu Dangi has officially said <strong>YES</strong> to being Akshit's Valentine.</li>
                    <li>Akshit Solanki promises to provide unlimited snacks and compliments.</li>
                    <li>This agreement is legally binding in the Kingdom of Romance.</li>
                </ul>

                <div style="margin-top: 30px; text-align: center;">
                    <p style="font-style: italic; color: #ff4d6d; font-size: 1.2rem;">"Signed with a digital kiss."</p>
                    <div style="font-family: 'Brush Script MT', cursive; font-size: 2rem; color: #333; margin-top: 10px;">
                        Accepted & Sealed
                    </div>
                </div>
            </div>
            <p style="text-align: center; color: #aaa; font-size: 0.8rem; margin-top: 20px;">
                Generated by your Valentine Prank Site | 2024
            </p>
        </body>
        </html>
        """
        
        msg.attach(MIMEText(body, 'html'))

        print("DEBUG: Connecting to SMTP server...")
        server = smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=20)
        server.set_debuglevel(1)  # This will output the full conversation to logs
        server.starttls()
        print("DEBUG: Logging in...")
        server.login(SMTP_USERNAME, SMTP_PASSWORD)
        print("DEBUG: Sending mail...")
        server.sendmail(SMTP_FROM_EMAIL, RECIPIENTS, msg.as_string())
        server.quit()
        
        print("DEBUG: Email sent successfully!")

        return {
            'statusCode': 200,
            'body': json.dumps({'status': 'success', 'message': 'Agreement sent!'}),
            'headers': {
                'Access-Control-Allow-Origin': '*',
                'Content-Type': 'application/json'
            }
        }
    except Exception as e:
        print(f"CRITICAL ERROR: {str(e)}")
        return {
            'statusCode': 500,
            'body': json.dumps({'status': 'error', 'message': str(e)}),
            'headers': {
                'Access-Control-Allow-Origin': '*',
                'Content-Type': 'application/json'
            }
        }
